backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
  branch: master # Branch to update (master by default)

media_folder: "themes/inbeat/source-images" # Folder where user uploaded files should go
public_folder: "/img" # The src attribute for uploaded media will begin with

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

publish_mode: editorial_workflow
site_url: https://www.inbeat.co
logo_url: https://www.inbeat.co/img/inbeat-logo.png

collections:
### ARTICLES
  - name: articles # Used in routes, e.g. /admin/collections/blog
    label: Articles # Used in the UI
    label_singular: Article
    folder: content/articles # The path to the folder where the documents are stored
    slug: "{{fields.slug}}"
    extension: md
    format: yaml-frontmatter
    preview_path: articles/{{slug}}
    editor:
      preview: true
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "i18nlanguage"
      value: "en"
    fields:
      - {label: "SEO Title", name: "title", widget: "string"}
      - {label: "SEO Description", name: "description", widget: "text"}
      - {label: "Title (H1)", name: "titre", widget: "string"}
      - {label: "Slug/Link (if link is https://www.inbeat.co/articles/test-article, value is test-article)", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
      - {label: "Share image", name: "image", widget: "image" , required: false, hint: "Recommended size is 1200px x 630px"}
      - {label: "Banner image", name: "headerimage", widget: "image", hint: "Recommended size is 1600px x 350px"}
      - {label: "Publication date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - label: "Categories" 
        name: "categories"
        widget: "select"
        multiple: true
        options: [ "General", "Tips" ]
      - label: "Author" 
        name: "author"
        widget: "select"
        options:
          - { label: "David Morneau", value: "david" }
      - {label: "Comments", name: "comments", widget: "number", default: 0}
      - {label: "Shares", name: "shares", widget: "number", default: 0}
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "en"}
      - {label: "Include popup style 1", name: "popupstyle1", widget: "boolean", default: false}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Hide from website?", name: "draft", widget: "boolean", default: false}
      - {label: "Remove from search engine?", name: "noindex", widget: "boolean", default: false}
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - name: "accueil"
        label: "Page d'accueil"
        file: "content/_index.md"
        description: "Texte de votre page d'accueil"
        fields:
          - {label: "SEO Title", name: "title", widget: "string"}
          - {label: "SEO Description", name: "description", widget: "text"}
          - {label: "Share image", name: "image", widget: "image" , required: false, hint: "Recommended size is 1200px x 630px"}
          - name: section1
            label: Section 1
            widget: object
            fields:
              - {label: "Petit Titre", name: "subtitle", widget: "string"}
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
          - name: section2
            label: Section 2
            widget: object
            fields:
              - name: points
                label: "Features"
                widget: list
                allow_add: false
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Icône", name: "icon", widget: "image"}
                  - {label: "Description", name: "description", widget: "text"}
          - name: section3
            label: Section 3
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image", hint: "Utilisez une image de 700px par 500px."}
          - name: section4
            label: Section 4
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image", hint: "Utilisez une image de 700px par 500px."}
          - name: section5
            label: Section 5
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image", hint: "Utilisez une image de 700px par 500px."}
          - name: section7
            label: Section 7
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - name: plans
                label: "Plans"
                widget: list
                allow_add: false
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Populaire?", name: "popular", widget: "boolean", required: false, default: false}
                  - {label: "Prix mensuel", name: "monthly", widget: "number"}
                  - {label: "Prix annuel", name: "yearly", widget: "number"}
                  - name: features
                    label: "Fonctionnalités"
                    widget: list
                    allow_add: true
                    fields:
                      - {label: "Texte", name: "text", widget: "string"}
                      - {label: "Rayé?", name: "disabled", widget: "boolean", required: false, default: false}
          - name: section8
            label: Section 8
            widget: object
            fields:
              - name: clients
                label: "Logos de clients"
                widget: list
                allow_add: false
                fields:
                  - {label: "Lien vers leur site", name: "link", widget: "string"}
                  - {label: "Logo", name: "logo", widget: "image", hint: "Utilisez un PNG de 150px de large, avec fond transparent."}
          - name: section9
            label: Section 9
            widget: object
            fields:
              - {label: "Texte", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
      - name: "terms-and-conditions"
        label: "Terms and Conditions"
        file: "content/singles/terms-and-conditions.md"
        description: "Text for Terms and Conditions"
        fields:
          - {label: "SEO Title", name: "title", widget: "string"}
          - {label: "SEO Description", name: "description", widget: "text"}
          - {label: "Slug/Link (if link is https://www.inbeat.co/articles/test-article, value is test-article)", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
          - {label: "Share image", name: "image", widget: "image" , required: false, hint: "Recommended size is 1200px x 630px"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "normal"}
          - {label: "Text", name: "body", widget: "markdown"}
          - {label: "Hide from website?", name: "draft", widget: "boolean", default: false}
          - {label: "Remove from search engine?", name: "noindex", widget: "boolean", default: false}
##### SETTINGS
  - name: "autres"
    label: "Autres"
    editor:
      preview: false
    files:
      - name: "menu"
        label: "Menu"
        file: "data/menu.yml"
        description: "Menu"
        fields:
          - name: main
            label: Menu principal
            widget: list
            allow_add: false
            fields:
              - {label: "Texte", name: "fr", widget: "string"}
              - {label: "Lien", name: "link", widget: "hidden"}
              - {label: "Sous-menu", name: "submenu", widget: "boolean"}
              - name: links
                label: Liens
                widget: list
                allow_add: false
                fields:
                  - {label: "Texte", name: "fr", widget: "string"}
                  - {label: "Lien", name: "link", widget: "hidden"}
      - name: "settings"
        label: "Généralités"
        file: "data/settings.yml"
        description: "Généralités"
        fields:
          - name: socials
            label: Réseaux sociaux
            widget: object
            fields:
              - {label: "Facebook", name: "facebookurl", widget: "string", required: false}
              - {label: "Linkedin", name: "linkedinurl", widget: "string", required: false}
              - {label: "Twitter", name: "twitterurl", widget: "string", required: false}
              - {label: "Youtube", name: "youtubeurl", widget: "string", required: false}
              - {label: "Instagram", name: "instagramurl", widget: "string", required: false}
          - name: address
            label: Adresse
            widget: object
            fields:
              - {label: "Rue", name: "road", widget: "string"}
              - {label: "Appartement", name: "app", widget: "string", required: false}
              - {label: "Ville", name: "city", widget: "string"}
              - {label: "Province", name: "province", widget: "string"}
              - {label: "Code postal", name: "postal", widget: "string"}
              - {label: "Pays", name: "country", widget: "string"}
          - {label: "Téléphone", name: "phone", widget: "string"}
          - {label: "Téléphone (condensé)", name: "mphone", widget: "string"}
          - {label: "Courriel", name: "email", widget: "string"}
          - {name: sitedescription, label: "Description SEO par défaut", widget: "text", hint: "Ceci est la valeur pour la page d'accueil et la valeur par défaut pour toutes les pages."}
          - {name: sitetitle, label: "Titre SEO par défaut", widget: "string", hint: "Ceci est la valeur pour la page d'accueil et la valeur par défaut pour toutes les pages."}
          - {label: "Image de partage par défaut", name: "defaultsocialimage", widget: "image", hint: "Ceci est la valeur pour la page d'accueil et la valeur par défaut pour toutes les pages."}
          - {label: "Enlever des moteurs de recherche", name: "removefromexternalsearch", widget: "hidden", default: false}
      - name: "popup"
        label: "Popup"
        file: "data/popup.yml"
        description: "Popup"
        fields:
          - name: popups
            label: Popups
            widget: object
            fields:
              - name: style1
                label: Popup style 1
                widget: object
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}